version: '3'
services:
  e:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
  volumes:
    - data/elastic/data:/usr/share/elasticsearch/data
  ports:
    - 9200:9200

  l:
    image: docker.elastic.co/logstash/logstash:7.9.1