version: '3'
volumes:
  e-data:
    driver: local
services:
  e:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: es01
    environment:
      - node.name=es01
      - xpack.security.enabled=false
      - discovery.type=single-node
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es02,es03
#      - cluster.initial_master_nodes=es01
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - e-data:/usr/share/elasticsearch/data
#      - ./data/elastic/data:/usr/share/elasticsearch/data
#      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300

  l:
    image: docker.elastic.co/logstash/logstash:7.9.2
    ports:
      - 9600:9600
    volumes:
      - ./logstash-simple.conf:/etc/logstash/conf.d/logstash.conf:ro

  k:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - MONITORING_ENABLED=monitoring.enabled
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
