version: '3'
volumes:
  app-logs:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    ports:
      - 9600:9600
      - 5044:5044
    volumes:
    - ./data/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
    - app-logs:/opt

  app:
    image: elk-app:latest
    ports:
    - 8080:8080
    volumes:
      - app-logs:/app/logs